sensor:
  - platform: sht4x
    temperature:
      name: "Temperature (SHT40)"
      filters:
        - offset: ${temp_sht40_offset}
    humidity:
      name: "Humidity (SHT40)"
    update_interval: 10s
