packages:
  base: !include common/.base_device.yaml
  board: !include common/.board.s3_micro.yaml

# i2c:
#   sda: GPIO17
#   scl: GPIO21

sensor:
  # - platform: scd4x
  #   co2:
  #     name: "CO2"
  #   temperature:
  #     name: "Temperature"
  #     filters:
  #       - sliding_window_moving_average:
  #           window_size: 10 # Average over this number of last measurements
  #           send_every: 2 # When sensor update interval is 30s, new value will be pushed every minute
  #   humidity:
  #     name: "Humidity"
  #   temperature_offset: 4.55
  #   update_interval: 30s
  - platform: dallas_temp
    id: floor_temp
    address: ${temp_floor_address}
    name: "Floor Temperature"
    one_wire_id: dallas_floor
    accuracy_decimals: 2
    update_interval: 30s
    filters:
      - sliding_window_moving_average:
          window_size: 5 # Average over this number of last measurements
          send_every: 2 # When sensor update interval is 30s, new value will be pushed every minute
  - platform: dallas_temp
    id: room_temp
    address: ${temp_room_address}
    name: "Temperature"
    one_wire_id: dallas_room
    accuracy_decimals: 2
    update_interval: 30s
    filters:
      - sliding_window_moving_average:
          window_size: 5 # Average over this number of last measurements
          send_every: 2 # When sensor update interval is 30s, new value will be pushed every minute

one_wire:
  - platform: gpio
    pin: GPIO4
    id: dallas_floor
  - platform: gpio
    pin: GPIO2
    id: dallas_room

light:
  - platform: esp32_rmt_led_strip
    id: status_light
    rgb_order: GRB
    pin: GPIO21
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    name: "Status light"
    internal: True

esphome:
  on_boot:
    then:
      - light.turn_off:
          id: status_light
          transition_length: 0s
