sensor:
  - platform: scd4x
    id: scd_sensor
    temperature:
      name: "Temperature (SCD41)"
      accuracy_decimals: 2
      # filters:
      #   - exponential_moving_average:
      #       alpha: 0.1
      #       send_every: 10
    humidity:
      name: "Humidity (SCD41)"
      accuracy_decimals: 2
    co2:
      name: "CO2 (SCD41)"
    temperature_offset: ${temp_scd41_offset}
    update_interval: 30s

button:
  - platform: template
    id: scd_calibratrion
    entity_category: config
    name: "Calibrate SCD"
    on_press:
      then:
        - scd4x.perform_forced_calibration:
            value: 425
            id: scd_sensor
  - platform: template
    id: scd_reset
    entity_category: config
    name: "Factory reset SCD"
    on_press:
      then:
        - scd4x.factory_reset: scd_sensor
