sensor:
  - platform: bme280_i2c
    address: 0x76
    temperature:
      name: "Temperature (BME280)"
      accuracy_decimals: 2
      filters:
        - offset: ${temp_room_offset}
        # - exponential_moving_average:
        #     alpha: 0.1
        #     send_every: 5
    pressure:
      name: "Pressure (BME280)"
      accuracy_decimals: 2
    humidity:
      name: "Humidity (BME280)"
      accuracy_decimals: 2
    iir_filter: 16x
    update_interval: 20s
