bme68x_bsec2_i2c:
  model: bme680
  address: 0x77
  temperature_offset: ${temp_room_offset}

sensor:
  - platform: bme68x_bsec2
    temperature:
      name: "Temperature (BME680)"
      accuracy_decimals: 2
    pressure:
      name: "Pressure (BME680)"
      accuracy_decimals: 2
    humidity:
      name: "Humidity (BME680)"
      accuracy_decimals: 2
    gas_resistance:
      name: "Gas resistance (BME680)"
    iaq:
      name: "IAQ (BME680)"
    iaq_static:
      name: "IAQ Static (BME680)"
    co2_equivalent:
      name: "CO2 Equivalent (BME680)"
    breath_voc_equivalent:
      name: "Breath VOC Equivalent (BME680)"

text_sensor:
  - platform: bme68x_bsec2
    iaq_accuracy:
      name: "IAQ Accuracy (BME680)"
